<?php

function migrate_vegwa_register_migrations() {

  // $common_arguments = array(
  //   'source_version' => 6,
  //   // 'group' => 'example',
  //   'source_connection' => 'legacy',
  //   'source_database' => array(
  //     'driver' => 'mysql',
  //     'database' => 'springweb',
  //   'username' => 'root', // Ideally this user has readonly access
  //   // Best practice: use a variable (defined by setting $conf in settings.php, or
  //   // with drush vset) for the password rather than exposing it in the code.
  //   'password' => 'root',
  //   'host' => 'localhost',
  //   'prefix' => '',
  //   ),
  //   );

}
